version: "3.8"

services:
  # 1. Real-Time Communication (RTC) Service
  livekit:
    image: livekit/livekit-server:latest # Using latest tag as specific versions were not found
    container_name: livekit_server
    restart: unless-stopped
    ports:
      - "7880:7880"        # API and WebSocket (for client connections)
      - "7881:7881"        # WebRTC over TCP/TLS
      - "50000-60000:50000-60000/udp" # WebRTC over UDP for better performance
    volumes:
      - ./rtc/livekit.yaml:/etc/livekit.yaml
    environment:
      # Keys are passed from the .env file for security
      - LIVEKIT_KEYS=${LIVEKIT_API_KEY}:${LIVEKIT_API_SECRET}
    env_file:
      - .env

  # 2. Voice Activity Detection (VAD) Service
  vad:
    build: ./vad
    container_name: vad_service
    restart: unless-stopped
    ports:
      - "8000:8000"

  # 3. Speech-to-Text (STT) Service with GPU acceleration
  stt:
    build: ./stt
    container_name: stt_service
    restart: unless-stopped
    ports:
      - "8001:8001"
    # This section enables GPU access for the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # Requesting one GPU
              capabilities: [gpu]

  # 4. Text-to-Speech (TTS) Service
  tts:
    build: ./tts
    container_name: tts_service
    restart: unless-stopped
    ports:
      - "8002:8002"

  # 5. Orchestration Service (The "Brain")
  orchestrator:
    build: ./orchestrator
    container_name: orchestrator_service
    restart: unless-stopped
    depends_on:
      - livekit
      - vad
      - stt
      - tts
    environment:
      # The orchestrator connects to other services using their service names
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - ROOM_NAME=bangla-voice-agent
      - VAD_URL=http://vad:8000/detect_speech
      - STT_URL=http://stt:8001/transcribe
      - TTS_URL=http://tts:8002/synthesize
      - GOVT_API_URL=http://114.130.116.74/govtchat/chat/stream
    env_file:
      - .env

  # 6. Frontend Web Server
  frontend:
    image: nginx:1.25-alpine
    container_name: frontend_server
    restart: unless-stopped
    ports:
      - "8080:80" # Expose frontend on host port 8080
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      # These variables will be injected into the JavaScript file
      - LIVEKIT_URL=ws://localhost:7880
      - LIVEKIT_FRONTEND_TOKEN=${LIVEKIT_FRONTEND_TOKEN}
    env_file:
      - .env
    # This command uses `envsubst` to substitute environment variables in the JS template.
    # It reads the template, replaces placeholders like `${LIVEKIT_URL}` with their
    # values from the environment, and writes the result to the final script.js
    # before starting the Nginx server.
    command: /bin/sh -c 'envsubst < /usr/share/nginx/html/script.js.template > /usr/share/nginx/html/script.js && nginx -g "daemon off;"'
